apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-tcp-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.20
  ports:
  - name: dns
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
