apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web
    image: dtoporin/my-web-app:1.0
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
    livenessProbe:
      tcpSocket:
         port: 8000
      initialDelaySeconds: 15
      periodSeconds: 20
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
        - mountPath: /app
          name: web
  initContainers:
    - name: init
      image: busybox:1.31.1
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - mountPath: /app
          name: web
  volumes:
    - name:  web
      emptyDir: {}
